#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelViewUI.Views
{
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

#line 2 "Login.cshtml"
using PortableRazor;

#line default
#line hidden


[System.CodeDom.Compiler.GeneratedCodeAttribute("RazorTemplatePreprocessor", "4.7.10.22")]
public partial class Login : PortableRazor.ViewBase
{

#line hidden

public override void Execute()
{
WriteLiteral("\r\n\r\n<!DOCTYPE html>\r\n<html");

WriteLiteral(" lang=\"en-US\"");

WriteLiteral(">\r\n\r\n    <head>\r\n    <meta");

WriteLiteral(" charset=\"utf-8\"");

WriteLiteral(" />\r\n    <meta");

WriteLiteral(" http-equiv=\"X-UA-Compatible\"");

WriteLiteral(" content=\"IE=edge\"");

WriteLiteral(">\r\n    <meta");

WriteLiteral(" name=\"viewport\"");

WriteLiteral(" content=\"width=device-width, initial-scale=1, maximum-scale=1, user-scalable=0\"");

WriteLiteral(" />\r\n    <title>Black Framework</title>\r\n    <link");

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" type=\"text/css\"");

WriteLiteral(" href=\"css/style.css\"");

WriteLiteral(">\r\n    <link");

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" type=\"text/css\"");

WriteLiteral(" href=\"css/font-awesome.css\"");

WriteLiteral(">\r\n    <script");

WriteLiteral(" src=\"jquery-1.11.3.min.js\"");

WriteLiteral("></script>\r\n      \r\n    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(@">

        $(document).ready(function ()
        {
            var os = navigator.platform

            if (os == ""iPad"")
            {
                $('head').append('<link rel=""stylesheet"" href=""css/styleIOS.css"" type=""text/css"" />');

            }
            else
            {
                $('head').append('<link rel=""stylesheet"" href=""css/style.css"" type=""text/css"" />');
            }
        });

        function UserLogin() {

            var password = document.getElementById('txtPassword').value;
            var user = document.getElementById('txtuser').value;

            ");

WriteLiteral("\r\n        }\r\n    </script>\r\n\r\n\r\n    </head>\r\n\r\n    <body>\r\n        <img");

WriteLiteral(" />\r\n        <div");

WriteLiteral(" class=\"width100\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"width100\"");

WriteLiteral(">\r\n                <img");

WriteLiteral(" src=\"Images/top-banner.png\"");

WriteLiteral(" class=\"img-responsiv\"");

WriteLiteral(">\r\n            </div>\r\n\r\n        </div>\r\n\r\n        <div");

WriteLiteral(" class=\"width100 top30 textCenter\"");

WriteLiteral(">\r\n            <p");

WriteLiteral(" class=\"welcomeHd bottomPad5\"");

WriteLiteral(">Welcome </p>\r\n        </div>\r\n\r\n        <div");

WriteLiteral(" class=\"width100 top40\"");

WriteLiteral(">\r\n            <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" class=\"inputLogin\"");

WriteLiteral(" id=\"txtuser\"");

WriteLiteral(" name=\"\"");

WriteLiteral(" placeholder=\"Sales Diary User ID\"");

WriteLiteral(">\r\n        </div>\r\n\r\n        <div");

WriteLiteral(" class=\"width100 top20\"");

WriteLiteral(">\r\n            <input");

WriteLiteral(" type=\"password\"");

WriteLiteral(" class=\"inputLogin\"");

WriteLiteral(" id=\"txtPassword\"");

WriteLiteral(" name=\"\"");

WriteLiteral(" placeholder=\"Password\"");

WriteLiteral(">\r\n        </div>\r\n\r\n        <div");

WriteLiteral(" class=\"width90 forgot-pas\"");

WriteLiteral(">\r\n            forgot password?\r\n        </div>\r\n\r\n        <div");

WriteLiteral(" class=\"width100 top30\"");

WriteLiteral(">\r\n            <input");

WriteLiteral(" class=\"loginBt\"");

WriteLiteral(" type=\"button\"");

WriteLiteral(" value=\"Login\"");

WriteLiteral(" onclick=\"UserLogin()\"");

WriteLiteral(" />\r\n\r\n            <p");

WriteLiteral(" class=\"width80 textCenter margincenter top10\"");

WriteLiteral("> \r\n                By logging to this application you agree all the terms and co" +
"nditions\r\n            </p>\r\n        </div>\r\n\r\n        <div");

WriteLiteral(" class=\"width40 margincenter textCenter\"");

WriteLiteral(">\r\n            <img");

WriteLiteral(" src=\"Images/logo.png\"");

WriteLiteral(" class=\"top20\"");

WriteLiteral("/>\r\n        </div>\r\n\r\n        <p");

WriteLiteral(" class=\"width90 authorizTxt top10\"");

WriteLiteral(">\r\n            This application is intended for Tata AIA Life employees and autho" +
"rized partners only<br />\r\n            <b>PROD 1.1.29</b>\r\n        </p>\r\n\r\n    <" +
"/body>\r\n\r\n</html>");

}
}
}
#pragma warning restore 1591
